<?php

namespace hepia\ThanatosBundle\Repository;
use Doctrine\ORM\Tools\Pagination\Paginator;

/**
 * InstanceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InstanceRepository extends \Doctrine\ORM\EntityRepository {

    public function getInstanceById($id) {
        $entity = $this->_em
                ->getRepository('hepiaThanatosBundle:Instance')
                ->createQueryBuilder('e')
                ->select('e', 'n')
                ->join('e.network', 'n')
                ->join('e.data', 'd')
                ->where('e.id = ' . $id)
                ->getQuery()
                ->getResult();
        return $entity;
    }

    public function getList($id, $page = 1, $maxperpage = 10) {
        $q = $this->_em->getRepository('hepiaThanatosBundle:Instance')->createQueryBuilder('e')->select('e')->where('e.project = ' . $id);
        $q->orderBy('e.id', 'DESC')->setFirstResult(($page - 1) * $maxperpage)->setMaxResults($maxperpage);
        return new Paginator($q);
    }

    public function countPublishedTotal($id) {
        return $this->createQueryBuilder('l')->select('COUNT(l)')->where('l.project = ' . $id)->getQuery()->getSingleScalarResult();
    }

}
