<?php

namespace hepia\ThanatosBundle\Repository;
use Doctrine\ORM\Tools\Pagination\Paginator;

/**
 * networkRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NetworkRepository extends \Doctrine\ORM\EntityRepository {

    public function getList($page = 1, $maxperpage = 10) {
        $q = $this->_em->getRepository('hepiaThanatosBundle:Network')->createQueryBuilder('e')->select('e');
        $q->orderBy('e.id', 'DESC')->setFirstResult(($page - 1) * $maxperpage)->setMaxResults($maxperpage);
        return new Paginator($q);
    }

    public function countPublishedTotal() {
        return $this->createQueryBuilder('l')->select('COUNT(l)')->getQuery()->getSingleScalarResult();
    }

}
