<?php

namespace hepia\ThanatosBundle\Repository;

/**
 * ValidationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ValidationRepository extends \Doctrine\ORM\EntityRepository {

    public function countPublishedTotal($id) {
        return $this->createQueryBuilder('l')->select('COUNT(l)')->where('l.instance = ' . $id)->getQuery()->getSingleScalarResult();
    }

}
